"""Root portal mirror generation."""

from __future__ import annotations

from pathlib import Path

from .io import ensure_dir, read_yaml, write_text
from .paths import VibePaths


GENERATED_NOTICE = "<!-- GENERATED by VibeResearch from .vibe/portal; do not edit this root mirror directly. -->"

ROOT_MIRRORS = [
    "RUN.md",
    "VIBE_STATUS.md",
    "VIBE_TODO.md",
    "VIBE_TIMELINE.md",
    "VIBE_LEADERBOARD.md",
    "CURRENT_RESEARCH_BRIEF.md",
]


def portal_mode(paths: VibePaths, explicit: str | None = None) -> str:
    if explicit:
        return explicit
    config = read_yaml(paths.vibe / "config.yaml", {})
    if isinstance(config, dict):
        portal = config.get("portal", {})
        if isinstance(portal, dict):
            return str(portal.get("root_mode") or "copy")
    return "copy"


def with_notice(text: str) -> str:
    body = text if text.endswith("\n") else f"{text}\n"
    if body.startswith(GENERATED_NOTICE):
        return body
    return f"{GENERATED_NOTICE}\n\n{body}"


def write_portal_text(paths: VibePaths, name: str, text: str) -> Path:
    if name not in ROOT_MIRRORS and name not in {"AGENTS.md", "AGENTS_SNIPPET.md", "INSTALL.md", "USAGE.md"}:
        raise ValueError(f"Unsupported portal file: {name}")
    target = paths.portal / name
    write_text(target, with_notice(text))
    return target


def root_mirror_is_managed(path: Path) -> bool:
    if path.is_symlink():
        return True
    if not path.exists():
        return True
    try:
        return path.read_text().startswith(GENERATED_NOTICE)
    except UnicodeDecodeError:
        return False


def build_portal(paths: VibePaths, *, mode: str | None = None, force: bool = False) -> list[Path]:
    selected = portal_mode(paths, mode)
    if selected == "none":
        return []
    if selected not in {"copy", "symlink"}:
        raise ValueError(f"Unsupported root portal mode: {selected}")
    ensure_dir(paths.portal)
    written: list[Path] = []
    for name in ROOT_MIRRORS:
        source = paths.portal / name
        if not source.exists():
            continue
        target = paths.root / name
        if not force and not root_mirror_is_managed(target):
            continue
        if target.exists() or target.is_symlink():
            target.unlink(missing_ok=True)
        if selected == "symlink":
            target.symlink_to(source.relative_to(paths.root))
        else:
            write_text(target, source.read_text())
        written.append(target)
    return written


def agents_snippet(project_name: str) -> str:
    return f"""# VibeResearch Operator Snippet

This repository uses VibeResearch state under `.vibe/`.

- Check `vibe status` and `vibe next` before starting autonomous research work.
- Treat root `VIBE_*.md` files and `RUN.md` as generated mirrors of `.vibe/portal/`.
- Do not edit `.vibe/state/`, `.vibe/scheduler/`, or `.vibe/leaderboard/` by hand unless the user explicitly asks.
- Keep generated research artifacts scoped to the active run, cycle, or research folder.

Project: `{project_name}`
"""


def write_agents_files(paths: VibePaths, project_name: str) -> None:
    snippet = agents_snippet(project_name)
    write_text(paths.vibe / "AGENTS_SNIPPET.md", with_notice(snippet))
    write_text(paths.vibe / "AGENTS.md", with_notice(snippet))
    write_portal_text(paths, "AGENTS_SNIPPET.md", snippet)


def install_agents_snippet(paths: VibePaths) -> bool:
    snippet_path = paths.vibe / "AGENTS_SNIPPET.md"
    if not snippet_path.exists():
        return False
    target = paths.root / "AGENTS.md"
    snippet = snippet_path.read_text()
    marker_start = "<!-- VIBERESEARCH_AGENTS_SNIPPET_START -->"
    marker_end = "<!-- VIBERESEARCH_AGENTS_SNIPPET_END -->"
    block = f"{marker_start}\n{snippet.rstrip()}\n{marker_end}\n"
    if target.exists():
        text = target.read_text()
        if marker_start in text and marker_end in text:
            before = text.split(marker_start, 1)[0]
            after = text.split(marker_end, 1)[1].lstrip("\n")
            target.write_text(f"{before}{block}\n{after}".rstrip() + "\n")
        else:
            target.write_text(text.rstrip() + "\n\n" + block)
    else:
        target.write_text(block)
    return True
