"""Execution script bootstrap helpers for downstream repositories."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .adapters import is_placeholder_command
from .io import ensure_dir, read_json, utc_now, write_json, write_text
from .paths import VibePaths


INSTRUMENTATION_WRAPPERS = [
    "environment_probe",
    "data_probe",
    "baseline_inventory",
    "evaluation_smoke",
    "metrics_export",
]
EXPERIMENT_WRAPPERS = ["baseline_compare", "train_smoke", "train_gate", "long_run_submit"]


def default_script_dir(paths: VibePaths) -> Path:
    return paths.vibe / "scripts"


def bootstrap_script_plan(paths: VibePaths, *, script_dir: str = ".vibe/scripts", generate: bool = True) -> Path:
    target_dir = paths.root / script_dir
    wrappers = INSTRUMENTATION_WRAPPERS + EXPERIMENT_WRAPPERS
    lines = [
        "# VibeResearch Script Bootstrap Plan",
        "",
        f"Generated at: `{utc_now()}`",
        f"Script directory: `{script_dir}`",
        "",
        "Generated wrappers are draft and untrusted until lint, contract-test, and adapter activation pass.",
        "",
        "## Recommended Wrappers",
        "",
    ]
    for name in wrappers:
        lines.extend(
            [
                f"### {name}",
                "",
                "- Purpose: provide a thin project-owned wrapper for this capability.",
                "- Existing entrypoint: unresolved by bootstrap discovery.",
                "- Required inputs: project-specific; answer adapter questions before activation.",
                "- Expected outputs: schema-valid metrics/artifacts declared in `.vibe/adapter.yaml`.",
                "- Contract test: dryrun must execute and expected metrics/artifacts must be produced or mocked.",
                "- Activation blockers: missing user answers, metrics schema, artifact rules, resource policy, or contract test.",
                "",
            ]
        )
    write_text(paths.vibe / "script_bootstrap_plan.md", "\n".join(lines))
    if generate:
        ensure_dir(target_dir)
        for name in wrappers:
            write_wrapper(target_dir / f"{name}.py", name)
    script_readiness_matrix(paths, script_dir=script_dir, write=True)
    return paths.vibe / "script_bootstrap_plan.md"


def write_wrapper(path: Path, capability_id: str) -> None:
    text = f'''#!/usr/bin/env python3
"""Draft VibeResearch wrapper for {capability_id}.

Generated by VibeResearch adapter bootstrap.
Generated at: {utc_now()}
Linked adapter capability: {capability_id}
Source entrypoint: unresolved; replace this thin wrapper with a project-owned call.
Review/contract status: draft_untrusted
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dryrun", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    parser.add_argument("--metrics-out", default=".vibe/bootstrap_metrics/{capability_id}.json")
    args = parser.parse_args()
    out = pathlib.Path(args.metrics_out)
    out.parent.mkdir(parents=True, exist_ok=True)
    if args.dryrun:
        out.write_text(json.dumps({{"primary": 0.0, "mode": "dryrun"}}) + "\\n")
        return 0
    if "{capability_id}" == "metrics_export" or args.smoke:
        out.write_text(json.dumps({{"primary": 1.0, "mode": "smoke"}}) + "\\n")
        return 0
    print("Draft wrapper is not active. Replace with project-specific logic before activation.", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
'''
    write_text(path, text)
    try:
        path.chmod(0o755)
    except OSError:
        pass


def wrapper_inventory(paths: VibePaths, *, script_dir: str = ".vibe/scripts") -> list[dict[str, Any]]:
    root = paths.root / script_dir
    rows: list[dict[str, Any]] = []
    for name in INSTRUMENTATION_WRAPPERS + EXPERIMENT_WRAPPERS:
        path = root / f"{name}.py"
        rows.append({"id": name, "path": str(path), "exists": path.exists(), "status": "draft_untrusted" if path.exists() else "missing"})
    return rows


def script_readiness_matrix(paths: VibePaths, *, script_dir: str = ".vibe/scripts", write: bool = False) -> list[dict[str, Any]]:
    """Return script readiness with contract-oriented status fields."""

    root = paths.root / script_dir
    rows: list[dict[str, Any]] = []
    contract_dir = paths.vibe / "contract_tests"
    for name in INSTRUMENTATION_WRAPPERS + EXPERIMENT_WRAPPERS:
        path = root / f"{name}.py"
        contract = read_json(contract_dir / f"{name}.json", {}) if contract_dir.exists() else {}
        text = path.read_text(errors="ignore") if path.exists() else ""
        generated = "Generated by VibeResearch adapter bootstrap" in text
        placeholder = (not path.exists()) or is_placeholder_command(text[:300]) or "Draft wrapper is not active" in text
        status = "missing"
        if path.exists():
            status = "generated_draft" if generated else "existing"
            if placeholder:
                status = "needs_user_review"
            if name in {"evaluation_smoke", "baseline_compare"} and not project_eval_candidates(paths):
                status = "blocked_missing_project_eval"
            if contract.get("status") == "failed":
                status = "contract_failed"
            if contract.get("status") == "passed":
                status = "contract_passed" if generated else "active_reference"
        rows.append(
            {
                "id": name,
                "path": str(path.relative_to(paths.root)) if path.exists() else str(path),
                "exists": path.exists(),
                "status": status,
                "provenance": {"generated_by": "vibe script bootstrap" if generated else "project", "checked_at": utc_now()},
                "referenced_project_script": project_eval_candidates(paths)[:5],
                "input_contract": "project-specific; must be declared by adapter capability",
                "output_contract": f".vibe/bootstrap_metrics/{name}.json",
                "metrics_export_contract": "schema-valid JSON metrics required before trust",
                "dryrun_mode": "--dryrun",
                "smoke_mode": "--smoke",
                "failure_behavior": "non-zero exit or missing expected output blocks activation",
            }
        )
    if write:
        write_json(paths.vibe / "script_readiness.json", rows)
    return rows


def project_eval_candidates(paths: VibePaths) -> list[str]:
    candidates = []
    for pattern in ["*eval*.py", "*evaluate*.py", "*metric*.py", "*benchmark*.py"]:
        for path in sorted(paths.root.rglob(pattern)):
            if ".git" in path.parts or ".vibe" in path.parts or ".vibe_dogfood" in path.parts:
                continue
            if path.is_file():
                candidates.append(str(path.relative_to(paths.root)))
            if len(candidates) >= 20:
                return candidates
    return candidates
