"""Execution script bootstrap helpers for downstream repositories."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .io import ensure_dir, utc_now, write_text
from .paths import VibePaths


INSTRUMENTATION_WRAPPERS = [
    "environment_probe",
    "data_probe",
    "baseline_inventory",
    "evaluation_smoke",
    "metrics_export",
]
EXPERIMENT_WRAPPERS = ["baseline_compare", "train_smoke", "train_gate", "long_run_submit"]


def default_script_dir(paths: VibePaths) -> Path:
    return paths.vibe / "scripts"


def bootstrap_script_plan(paths: VibePaths, *, script_dir: str = ".vibe/scripts", generate: bool = True) -> Path:
    target_dir = paths.root / script_dir
    wrappers = INSTRUMENTATION_WRAPPERS + EXPERIMENT_WRAPPERS
    lines = [
        "# VibeResearch Script Bootstrap Plan",
        "",
        f"Generated at: `{utc_now()}`",
        f"Script directory: `{script_dir}`",
        "",
        "Generated wrappers are draft and untrusted until lint, contract-test, and adapter activation pass.",
        "",
        "## Recommended Wrappers",
        "",
    ]
    for name in wrappers:
        lines.extend(
            [
                f"### {name}",
                "",
                "- Purpose: provide a thin project-owned wrapper for this capability.",
                "- Existing entrypoint: unresolved by bootstrap discovery.",
                "- Required inputs: project-specific; answer adapter questions before activation.",
                "- Expected outputs: schema-valid metrics/artifacts declared in `.vibe/adapter.yaml`.",
                "- Contract test: dryrun must execute and expected metrics/artifacts must be produced or mocked.",
                "- Activation blockers: missing user answers, metrics schema, artifact rules, resource policy, or contract test.",
                "",
            ]
        )
    write_text(paths.vibe / "script_bootstrap_plan.md", "\n".join(lines))
    if generate:
        ensure_dir(target_dir)
        for name in wrappers:
            write_wrapper(target_dir / f"{name}.py", name)
    return paths.vibe / "script_bootstrap_plan.md"


def write_wrapper(path: Path, capability_id: str) -> None:
    text = f'''#!/usr/bin/env python3
"""Draft VibeResearch wrapper for {capability_id}.

Generated by VibeResearch adapter bootstrap.
Generated at: {utc_now()}
Linked adapter capability: {capability_id}
Source entrypoint: unresolved; replace this thin wrapper with a project-owned call.
Review/contract status: draft_untrusted
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dryrun", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    parser.add_argument("--metrics-out", default=".vibe/bootstrap_metrics/{capability_id}.json")
    args = parser.parse_args()
    out = pathlib.Path(args.metrics_out)
    out.parent.mkdir(parents=True, exist_ok=True)
    if args.dryrun:
        out.write_text(json.dumps({{"primary": 0.0, "mode": "dryrun"}}) + "\\n")
        return 0
    if "{capability_id}" == "metrics_export" or args.smoke:
        out.write_text(json.dumps({{"primary": 1.0, "mode": "smoke"}}) + "\\n")
        return 0
    print("Draft wrapper is not active. Replace with project-specific logic before activation.", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
'''
    write_text(path, text)
    try:
        path.chmod(0o755)
    except OSError:
        pass


def wrapper_inventory(paths: VibePaths, *, script_dir: str = ".vibe/scripts") -> list[dict[str, Any]]:
    root = paths.root / script_dir
    rows: list[dict[str, Any]] = []
    for name in INSTRUMENTATION_WRAPPERS + EXPERIMENT_WRAPPERS:
        path = root / f"{name}.py"
        rows.append({"id": name, "path": str(path), "exists": path.exists(), "status": "draft_untrusted" if path.exists() else "missing"})
    return rows
